### PR TITLE
chore: Add TruffleHog secrets scan to repo

### LINKED ISSUE #92: [Trufflehog Update] Add Trufflehog secret scanning workflow
## Description 

The GitGuardian secret scanning tool licence is now expired, therefore in order to maintain the Security of the Tractus-X Repositories there will be inforced the [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) for all Tractus-X repos.

## Main ticket
https://github.com/eclipse-tractusx/sig-security/issues/86

## What needs to be done?

- [ ] Add the Trufflehog workflow like described in [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) to the `/.github/workflows` folder
- [ ] Remove all references to GitGuardian from documentation
- [ ] Create a PR and Merge it to `main`
- [ ] As committer: revise if any secrets were found in the scan (in security tab)
- [ ] Close this ticket

Thank you very much for doing the update! 🚀 
If there is any question, please let us know,  

Your Tractus-X Project Leads 💯

### PR DESCRIPTION
**Pull request by lgblaumeiser**
## WHAT

Add a workflow to run TruffleHog secrets scanning to the repository

## WHY

General request to improve security according to TRG 8.03

## FURTHER NOTES

Closes #92

### CODE REVIEW

**Comment by lgblaumeiser** [comment]
Hi @paullatzelsperger, the Review Allowed Licenses workflow fails, due to the use of TruffleHog which is under AGPL license. I do not see this check in the Tractus-X EDC. What do you propose to handle the issue? Thanks!

**Comment by paullatzelsperger** [comment]
> Hi @paullatzelsperger, the Review Allowed Licenses workflow fails, due to the use of TruffleHog which is under AGPL license. I do not see this check in the Tractus-X EDC. What do you propose to handle the issue? Thanks!

These lines are the culprit: 
https://github.com/eclipse-tractusx/bpn-did-resolution-service/blob/e4a4fceba19e88ad411dde6bfed826e493bf2551/.github/workflows/verify.yaml#L67-L68

I would just remove them, since we have DASH anyways.

**Comment by paullatzelsperger** [comment]
@lgblaumeiser if you add the DASH check (see my previous comment) we can get this merged quickly

**Comment by lgblaumeiser** [comment]
Interesting, I thought, it was already there, as there is of course a DEPENDENCIES file and I remember, that I had to adapt it previously.

**Review by paullatzelsperger — APPROVED** [review]

**Pull request merged**
